/**
 * Client-side file generation for demo exports.
 *
 * Every Export/Download control in the demo produces a real file via a
 * Blob download — no dead affordances. Content is generated from the
 * on-screen fixture data and clearly stamped as a demo artifact.
 */

function trigger(filename, blob) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2000)
}

/** rows: array of objects (keys of the first row become the header). */
export function downloadCsv(filename, rows) {
  if (!rows?.length) return
  const cols = Object.keys(rows[0])
  const esc = (v) => {
    const s = String(v ?? '')
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
  }
  const csv = [cols.join(','), ...rows.map(r => cols.map(c => esc(r[c])).join(','))].join('\n')
  trigger(filename, new Blob([csv], { type: 'text/csv;charset=utf-8' }))
}

export function downloadJson(filename, data) {
  trigger(filename, new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }))
}

export function downloadText(filename, text) {
  trigger(filename, new Blob([text], { type: 'text/plain;charset=utf-8' }))
}

/** Simple self-contained HTML document (invoices, receipts, reports). */
export function downloadHtml(filename, title, bodyHtml) {
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>
<style>body{font-family:'IBM Plex Sans',system-ui,sans-serif;color:#0D092A;max-width:640px;margin:48px auto;padding:0 24px}
h1{font-size:20px}table{width:100%;border-collapse:collapse;margin:16px 0}td,th{padding:8px;border-bottom:1px solid #D8DCF5;text-align:left;font-size:14px}
.mono{font-family:'IBM Plex Mono',monospace;font-size:12px;color:#5E6582}</style></head>
<body><h1>${title}</h1>${bodyHtml}<p class="mono">Generated by arbitr · demo artifact</p></body></html>`
  trigger(filename, new Blob([html], { type: 'text/html;charset=utf-8' }))
}
